# -*- coding: utf-8 -*-
"""YOUTUBE-Chatbot-rag-using-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hOkVpz5bX81R1kYlozf43al-8mXux9M
"""

import os
os.environ["OPENAI_API_KEY"] = "Paste API HERE"

"""## Install libraries"""

!pip install -U langchain-text-splitters langchain-openai langchain-community faiss-cpu

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.documents import Document

"""## Step 1a - Indexing (Document Ingestion)"""

!pip install youtube-transcript-api

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
print(dir(YouTubeTranscriptApi)) # Verify 'list_transcripts' is now there

from youtube_transcript_api import YouTubeTranscriptApi

video_id = "Gfr50f6ZBvo"

try:
    # Initialize the API client
    api = YouTubeTranscriptApi()

    # Fetch the transcript data
    transcript_data = api.fetch(video_id)

    # 1. Format into the list of dictionaries
    formatted_transcript = [
        {
            'text': t.text,
            'start': t.start,
            'duration': t.duration
        }
        for t in transcript_data
    ]

    # 2. Create timestamped documents so downstream chunks preserve source times
    transcript_documents = [
        Document(
            page_content=t.text,
            metadata={
                "start": t.start,
                "duration": t.duration,
            },
        )
        for t in transcript_data
    ]

    # 3. Create the flattened string for quick inspection
    transcript_text = " ".join([t.text for t in transcript_data])

    # Print the result to verify
    import json
    print(json.dumps(formatted_transcript[:2], indent=2))
    print("\nTranscript preview:", transcript_text[:100] + "...")

except Exception as e:
    print(f"Error: {e}")

transcript = formatted_transcript

"""## Step 1b - Indexing (Text Splitting)"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)


def format_timestamp(seconds):
    total_seconds = int(seconds)
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    remaining_seconds = total_seconds % 60
    if hours:
        return f"{hours:02d}:{minutes:02d}:{remaining_seconds:02d}"
    return f"{minutes:02d}:{remaining_seconds:02d}"


chunks = splitter.split_documents(transcript_documents)


def format_retrieved_context(retrieved_docs):
    context_lines = []
    for doc in retrieved_docs:
        start = doc.metadata.get("start", 0)
        duration = doc.metadata.get("duration", 0)
        end = start + duration
        context_lines.append(
            f"[source: {format_timestamp(start)}-{format_timestamp(end)}] {doc.page_content}"
        )
    return "\n\n".join(context_lines)

len(chunks)

chunks[10]

"""## Step 1c & 1d - Indexing (Embedding Generation and Storing in Vector Store)"""

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
vector_store = FAISS.from_documents(chunks, embeddings)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['2436bdb8-3f5f-49c6-8915-0c654c888700'])

"""## Step 2 - Retrieval"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})

retriever

retriever.invoke('What is deepmind')

"""## Step 3 - Augmentation"""

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.
            When you answer, include the source timestamp(s) from the transcript in parentheses, like (source: 00:12-00:18).

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

question          = "is the topic of nuclear fusion discussed in this video? if yes then what was discussed"
retrieved_docs    = retriever.invoke(question)

retrieved_docs

context_text = format_retrieved_context(retrieved_docs)
context_text

final_prompt = prompt.invoke({"context": context_text, "question": question})

final_prompt

"""## Step 4 - Generation"""

answer = llm.invoke(final_prompt)
print(answer.content)

"""## Building a Chain"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_retrieved_context),
    'question': RunnablePassthrough()
})

parallel_chain.invoke('who is Demis')

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser



main_chain.invoke('Can you summarize the video')

